module.exports = {
  'maytinh.net': 'MayTinh.net',
  'loc.vn': 'Loc.vn',
  'kysu.vn': 'KySu.vn',
  'metabox.vn': 'MetaBox.vn',
  't-d.vn': 'T-D.vn',
  'cdx.vn': 'CDX.vn',
  'ncd.com.vn': 'NCD.com.vn',
  'ketnoi.me': 'KetNoi.me',
  'ncdai.vn': 'ncdai.vn',
  'ncdai.net': 'ncdai.net',
  'ncdai.me': 'ncdai.me',
  'cotienxanh.com': 'CoTienXanh.com',
  'dai0.com': 'dai0.com',
  'cd8.net': 'cd8.net',
  'e.id.vn': 'e.id.vn',
  'e.io.vn': 'e.io.vn',
  'uah.me': 'UAH.me',
  'chanhdai.io.vn': 'ChanhDai.io.vn',
}
