module.exports = {
  'maytinh.net': 'MayTinh.net',
  'tienphonggroup.com': 'TienPhongGroup.com',
  'vietgreenfood.com': 'VietGreenFood.com',
  'maytinhviet.com': 'MayTinhViet.com',
  'vuanhadat.com': 'VuaNhaDat.com',
  'vuadidong.com': 'VuaDiDong.com',
  'bongngo.com': 'BongNgo.com',
  'khieunai.com': 'KhieuNai.com',
  'hugevietnam.com': 'HugeVietNam.com',
  'kysu.vn': 'kysu.vn',
  'topweb.vn': 'TopWeb.vn',
  'metabox.vn': 'MetaBox.vn',
  'cdx.vn': 'CDX.vn',
  'ncd.com.vn': 'NCD.com.vn',
  'ncd.io.vn': 'NCD.io.vn',
  'ketnoi.me': 'Ketnoi.me',
  'ncdai.net': 'ncdai.net',
  'ncdai.me': 'ncdai.me',
  'cd.name.vn': 'CD.name.vn',
  'xr.io.vn': 'XR.io.vn',
  'xr.ai.vn': 'XR.ai.vn',
  'cotienxanh.com': 'CoTienXanh.com'
}
