module.exports = {
  'tienphonggroup.com': 'TienPhongGroup.com',
  'vietgreenfood.com': 'VietGreenFood.com',
  'maytinhviet.com': 'MayTinhViet.com',
  'vuanhadat.com': 'VuaNhaDat.com',
  'vuadidong.com': 'VuaDiDong.com',
  'bongngo.com': 'BongNgo.com',
  'khieunai.com': 'KhieuNai.com',
  'hugevietnam.com': 'HugeVietNam.com',
  'kysu.vn': 'KySu.vn',
  'topweb.vn': 'TopWeb.vn',
  'metabox.vn': 'MetaBox.vn',
  'cdx.vn': 'CDX.vn',
  'xr.io.vn': 'XR.io.vn',
  'xr.ai.vn': 'XR.ai.vn',
  'cotienxanh.com': 'CoTienXanh.com',
};
